export default {
    'gradientContainer': 'flex h-screen w-screen',
    'headerContainer': 'flex-row pb-3 items-center mx-4 space-x-2 mt-4',
    'logoImage': 'h-7 w-7 p-4 rounded-full',
    'headerTextContainer': 'flex-1',
    'headerText': 'font-bold text-gray-400 text-xs',
    'logoContainer': 'items-center mt-4',
    'logoFullImage': 'h-150 w-150 p-10 rounded-full object-contain',
    'logoSignInImage': 'object-contain h-60 w-60',
    'appDescriptionContainer': 'items-center mt-4',
    'motoText': 'font-bold text-white text-2xl text-center',
    'descriptionText': 'font-semibold text-gray-200 text-xl text-center mt-5',
    'buttonsContainer': 'flex-row flex-1 items-center space-x-5 mt-4 justify-center',
    'modalContainer': 'pt-8 px-6',
}